### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by cjke**
Layout HorizontalSplit should return

### CODE REVIEW

**Comment by chantastic** [comment]
hi @cjke!

thanks for the PR.
sorry to have missed it.

Thanks @chefnobody!

Your approach seems right to me.
Sorry for the delay.
I've changed the structure of this repo quite a bit since your PR.

I'd love to merge your fix.

Two ways to proceed:
A. Rebase your fork and update the PR — you retain authorship credit.
B. I can merge locally — authorship gets lost.

Thanks,
Michael

**Comment by cjke** [comment]
I kind of forgot about this PR. I'm happy for you to do it locally - not fussed at all

**Comment by chantastic** [comment]
oh nice!
we were able to keep it linked!

thanks so much for your support in opening this PR.
I appreciate your help 🙌

**Comment by cjke** [comment]
Hey hey look at that!
No worries, its a very clean resource - happy to help

**Pull request merged**
